"""
DeepONet for 2-D curve prediction from 4-5 parameters (PyTorch)

This is a runnable example that:
 - generates a synthetic dataset of parameter -> curve pairs
 - implements a simple DeepONet (branch net for parameters, trunk net for x coordinate)
 - trains the network to predict y(x) given parameters and x
 - reconstructs full curves and plots examples

Notes:
 - If you already have dataset, adapt the Dataset class to load your data.
 - This implementation evaluates the network pointwise (params + x) but batches many x per param.
 - Requires: torch, numpy, matplotlib

Author: Generated by ChatGPT
"""

import math
import os
import random
from typing import Tuple

import numpy as np
import torch
from torch import nn
from torch.utils.data import DataLoader, Dataset
import matplotlib.pyplot as plt

# -------------------------------
# Config / Hyperparameters
# -------------------------------
SEED = 42
DEVICE = torch.device("cuda" if torch.cuda.is_available() else "cpu")
NUM_PARAMS = 5            # number of input parameters
CURVE_POINTS = 200        # resolution of curves when plotting / reconstructing
TRAIN_SAMPLES = 25     # number of distinct curves in training set
VAL_SAMPLES = 5         # validation curves
BATCH_SIZE = 256          # number of (param,x) pairs per batch
BRANCH_HIDDEN = [128, 128]
TRUNK_HIDDEN = [128, 128]
BRANCH_OUTPUT_DIM = 64    # size of latent representation from branch net
LR = 1e-3
EPOCHS = 80
PRINT_EVERY = 5

# reproducibility
random.seed(SEED)
np.random.seed(SEED)
torch.manual_seed(SEED)

# -------------------------------
# Synthetic dataset generator
# -------------------------------
# We construct curves y(x; p) = sum_{k=1..K} a_k(p) * phi_k(x)
# where phi_k are fixed basis functions (Gaussians / sines) and a_k are functions of params p.

def basis_functions(x: np.ndarray, K: int = 8) -> np.ndarray:
    """Return K basis functions evaluated at x. Shape: (K, len(x))"""
    xs = x.reshape(1, -1)
    centers = np.linspace(0.0, 1.0, K)
    widths = 0.08 + 0.02 * np.arange(K)

    gauss_basis = np.exp(-0.5 * ((xs - centers.reshape(-1, 1)) / widths.reshape(-1, 1)) ** 2)
    # Add some sinusoids
    k = np.arange(1, K + 1)
    sin_basis = np.sin(2 * math.pi * k.reshape(-1, 1) * xs)
    # Concatenate and take first K (to keep dimensionality stable)
    combined = np.vstack([gauss_basis, sin_basis])
    return combined[:K]


def param_to_coeffs(params: np.ndarray, K: int) -> np.ndarray:
    """Map parameter vector to K coefficients via a smooth nonlinear mapping.
    params: shape (NUM_PARAMS,)
    returns: shape (K,)"""
    # simple MLP-like mapping using sinusoids and linear transforms (deterministic)
    w = np.linspace(-1.0, 1.0, K * NUM_PARAMS).reshape(NUM_PARAMS, K)
    lin = params.reshape(1, -1).dot(w)  # shape (1, K)
    coeffs = np.tanh(lin).ravel() + 0.2 * np.sin(3.0 * lin).ravel()
    # scale to have different magnitudes per param
    scale = 1.0 / (1.0 + np.arange(K) * 0.1)
    return coeffs * scale


def make_curve(params: np.ndarray, x: np.ndarray) -> np.ndarray:
    K = 8
    B = basis_functions(x, K=K)  # (K, len(x))
    a = param_to_coeffs(params, K=K)  # (K,)
    y = a.reshape(-1, 1).T.dot(B)  # shape (1, len(x))
    y = y.ravel()
    # add a smooth envelope and small noise
    envelope = 1.0 + 0.3 * np.sin(2 * math.pi * 0.5 * x + 0.5 * params[0])
    y = envelope * y
    return y


class ParamCurveDataset(Dataset):
    """Dataset returning (params, x, y) pointwise for DeepONet training.
    If you prefer training on whole curves, modify accordingly.
    """
    def __init__(self, n_curves: int, curve_points: int = CURVE_POINTS):
        self.n_curves = n_curves
        self.curve_points = curve_points

        # sample parameters uniformly in some range
        self.params_all = np.random.uniform(low=-1.0, high=1.0, size=(n_curves, NUM_PARAMS)).astype(np.float32)
        self.x_grid = np.linspace(0.0, 1.0, curve_points).astype(np.float32)

        # precompute curves (so dataset returns pointwise pairs quickly)
        self.curves = np.empty((n_curves, curve_points), dtype=np.float32)
        for i in range(n_curves):
            self.curves[i] = make_curve(self.params_all[i], self.x_grid).astype(np.float32)

        # We'll expose the dataset as a collection of pointwise samples
        self.total_points = n_curves * curve_points

    def __len__(self):
        return self.total_points

    def __getitem__(self, idx):
        curve_idx = idx // self.curve_points
        x_idx = idx % self.curve_points
        p = self.params_all[curve_idx]
        x = self.x_grid[x_idx]
        y = self.curves[curve_idx, x_idx]
        # return as numpy arrays; DataLoader will collate to tensors
        return p, np.array([x], dtype=np.float32), np.array([y], dtype=np.float32)

# -------------------------------
# DeepONet models (branch + trunk)
# -------------------------------
class MLP(nn.Module):
    def __init__(self, in_dim, hidden, out_dim, activation=nn.ReLU):
        super().__init__()
        layers = []
        last = in_dim
        for h in hidden:
            layers.append(nn.Linear(last, h))
            layers.append(activation())
            last = h
        layers.append(nn.Linear(last, out_dim))
        self.net = nn.Sequential(*layers)

    def forward(self, x):
        return self.net(x)


class DeepONet(nn.Module):
    def __init__(self, param_dim: int, branch_out: int, trunk_out: int, branch_hidden, trunk_hidden):
        super().__init__()
        assert branch_out == trunk_out, "Branch and trunk output dims (basis size) must match"
        self.basis_dim = branch_out
        self.branch = MLP(param_dim, branch_hidden, branch_out)
        self.trunk = MLP(1, trunk_hidden, trunk_out)  # x is scalar
        # optional bias term
        self.register_parameter("bias", nn.Parameter(torch.zeros(1)))

    def forward(self, params: torch.Tensor, x: torch.Tensor) -> torch.Tensor:
        """
        params: (B, P) or (B, 1, P) depending on batching
        x: (B, 1) or (B, N, 1)
        We'll support flattened batching: both inputs should be (batch, ...)
        Returns: y_pred shape (batch, 1)
        """
        # ensure shapes: params -> (B, P); x -> (B, 1)
        b_params = params.view(params.size(0), -1)
        b_x = x.view(x.size(0), -1)
        # branch output: (B, basis_dim)
        br = self.branch(b_params)
        # trunk output: (B, basis_dim)
        tr = self.trunk(b_x)
        # inner product along basis dim
        out = torch.sum(br * tr, dim=1, keepdim=True) + self.bias
        return out

# -------------------------------
# Training utilities
# -------------------------------

def train_one_epoch(model, loader, opt, device):
    model.train()
    total_loss = 0.0
    for p_batch, x_batch, y_batch in loader:
        p_batch = p_batch.to(device)
        x_batch = x_batch.to(device)
        y_batch = y_batch.to(device)

        pred = model(p_batch, x_batch)
        loss = nn.functional.mse_loss(pred, y_batch)

        opt.zero_grad()
        loss.backward()
        opt.step()

        total_loss += loss.item() * p_batch.size(0)
    return total_loss / len(loader.dataset)


def evaluate(model, dataset: ParamCurveDataset, device, batch_size=1024) -> float:
    model.eval()
    loader = DataLoader(dataset, batch_size=batch_size, shuffle=False)
    tot = 0.0
    with torch.no_grad():
        for p_batch, x_batch, y_batch in loader:
            p_batch = p_batch.to(device)
            x_batch = x_batch.to(device)
            y_batch = y_batch.to(device)
            pred = model(p_batch, x_batch)
            loss = nn.functional.mse_loss(pred, y_batch, reduction='sum')
            tot += loss.item()
    return tot / len(loader.dataset)


def reconstruct_curve(model, params: np.ndarray, x_grid: np.ndarray, device) -> np.ndarray:
    model.eval()
    with torch.no_grad():
        P = params.astype(np.float32).reshape(1, -1)
        # evaluate for all x at once by repeating params
        X = x_grid.astype(np.float32).reshape(-1, 1)
        P_rep = np.repeat(P, X.shape[0], axis=0)
        p_t = torch.from_numpy(P_rep).to(device)
        x_t = torch.from_numpy(X).to(device)
        y_pred = model(p_t, x_t).cpu().numpy().ravel()
    return y_pred

# -------------------------------
# Run training + demo
# -------------------------------

def main():
    device = DEVICE
    print(f"Using device: {device}")

    train_ds = ParamCurveDataset(TRAIN_SAMPLES, curve_points=CURVE_POINTS)
    val_ds = ParamCurveDataset(VAL_SAMPLES, curve_points=CURVE_POINTS)

    # We train pointwise: create DataLoader that yields (params, x, y) as tensors
    def collate_fn(batch):
        p = np.stack([b[0] for b in batch], axis=0)
        x = np.stack([b[1] for b in batch], axis=0)
        y = np.stack([b[2] for b in batch], axis=0)
        return torch.from_numpy(p).float(), torch.from_numpy(x).float(), torch.from_numpy(y).float()

    train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, collate_fn=collate_fn)

    model = DeepONet(NUM_PARAMS, BRANCH_OUTPUT_DIM, BRANCH_OUTPUT_DIM, BRANCH_HIDDEN, TRUNK_HIDDEN).to(device)
    opt = torch.optim.Adam(model.parameters(), lr=LR, weight_decay=1e-5)

    best_val = float('inf')
    history = {'train':[], 'val':[]}

    for epoch in range(1, EPOCHS + 1):
        train_loss = train_one_epoch(model, train_loader, opt, device)
        val_loss = evaluate(model, val_ds, device)
        history['train'].append(train_loss)
        history['val'].append(val_loss)

        if epoch % PRINT_EVERY == 0 or epoch == 1:
            print(f"Epoch {epoch}/{EPOCHS}  train_loss={train_loss:.6f}  val_loss={val_loss:.6f}")

        if val_loss < best_val:
            best_val = val_loss
            torch.save(model.state_dict(), "deeponet_best.pth")

    print("Training finished. Best val loss:", best_val)

    # plot losses
    plt.figure(figsize=(6,4))
    plt.plot(history['train'], label='train')
    plt.plot(history['val'], label='val')
    plt.yscale('log')
    plt.legend()
    plt.title('Loss curves')
    plt.show()

    # plot some reconstructions
    x_grid = np.linspace(0.0, 1.0, CURVE_POINTS)
    n_examples = 4
    idxs = np.random.choice(len(val_ds.params_all), size=n_examples, replace=False)
    model.load_state_dict(torch.load("deeponet_best.pth", map_location=device))

    plt.figure(figsize=(10, 6))
    for i, idx in enumerate(idxs, 1):
        p = val_ds.params_all[idx]
        y_true = val_ds.curves[idx]
        y_pred = reconstruct_curve(model, p, x_grid, device)
        plt.subplot(n_examples, 1, i)
        plt.plot(x_grid, y_true, label='true')
        plt.plot(x_grid, y_pred, '--', label='pred')
        plt.title(f'Example {i} params={np.round(p,2)}')
        if i == 1:
            plt.legend()
    plt.tight_layout()
    plt.show()


if __name__ == '__main__':
    main()
